### ISSUE TITLE
.pdf.pdf

### ISSUE THREAD

**Issue by CodeMaxx** [nihal111/MooDLD#10]
Files already having .pdf in their name are downloaded as .pdf.pdf

**Comment by arpan98** [comment]
@CodeMaxx All files already have an extension with the filename, right? So we can just stop appending the extension at the end of the file?

**Comment by CodeMaxx** [comment]
Not all files are getting double extension.. maybe some bug in the code

**Comment by CodeMaxx** [comment]
@arpan98 We are checking the link but appending to file name. Checking of
the file name has extension will solve the problem

**Comment by arpan98** [comment]
The mechanism for checking if the file exists or not also needs to be updated along with this.

**Comment by CodeMaxx** [comment]
@arpan98 Why is that requried?

**Comment by arpan98** [comment]
@CodeMaxx When checking if the file already exists or not, we are checking against the `.pdf.pdf` filename. That needs to be changed as well.

**Comment by CodeMaxx** [comment]
Yeah that needs to be done

**Comment by CodeMaxx** [comment]
Solved
