### ISSUE TITLE
Random downloading destinations

### ISSUE THREAD

**Issue by abhi269** [nihal111/MooDLD#22]
Downloading files at random destinations.
first it  created a folder named newsforum in C:/
then downloaded some file in C:/newsforum and all other in C:/ 
the root directory was C:/

**Comment by nihal111** [comment]
That's not random. That's intended. You're clearly asked to set a download directory in the preferences screen. The default is C:/. If you select the root dir as C:/ then all course folders are created in C:/ and further news forum folders are created inside course folders. 
For course PH 108, if you set directory as C:/PH-108. It downloads all main thread files in C:/PH-108 and news forum files in C:/PH-108/News Forum. 
Setting the directory to C:/ was wrong and the behavior was intended. Set it to C:/courseName or whatever you want. Setting the root directory is the easiest way to achieve this.
