### ISSUE TITLE
progress circle goes negative

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/MooDLD#23]
![screenshot_20160816-121633](https://cloud.githubusercontent.com/assets/5952063/17690421/3221d638-63ac-11e6-975c-63527df4966a.png)

Android version : 6.0.1, Samsung Galaxy J7

**Comment by nihal111** [comment]
I would like you to uninstall and reinstall the latest play store version i.e v1.0.2 and then create an issue on the MooDLD-for-Android repository if it still exists. Thanks.

**Comment by cheekujodhpur** [comment]
Yeah I had reinstalled from PlayStore. This is with v1.0.2 I'll put an
issue there then
