### ISSUE TITLE
can't dismiss notification

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/MooDLD#24]
![Uploading Screenshot_20160816-122220.png…]()

I cannot dismiss the download complete notification. 

Android version is 6.0.1
Device: Samsung Galaxy J7

**Comment by cheekujodhpur** [comment]
![screenshot_20160816-122220](https://cloud.githubusercontent.com/assets/5952063/17690502/a2a98680-63ac-11e6-8885-63432d936a2d.png)

**Comment by nihal111** [comment]
This is known. We'll fix this. More issues on MooDLD-for-Android repository please.
